# Generated by Django 2.0.2 on 2018-04-01 16:56

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Disaster_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Record_date', models.DateField(auto_now_add=True)),
                ('Recod_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disaster_Record_Tweet_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetUtils.Disaster_Record')),
            ],
        ),
        migrations.CreateModel(
            name='Disaster_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disaster_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=25)),
                ('City', models.CharField(max_length=40)),
                ('Longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('Altitude', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tweet', models.TextField()),
                ('User_name', models.TextField()),
                ('Tweet_time', models.DateTimeField()),
                ('Tweet_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('Tweet_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='User_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetUtils.Location')),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user_location',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disaster_record_tweet_info',
            name='Tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetUtils.Tweet_Info'),
        ),
        migrations.AddField(
            model_name='disaster_record',
            name='Disaster_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetUtils.Disaster_Type'),
        ),
        migrations.AddField(
            model_name='disaster_record',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetUtils.Location'),
        ),
        migrations.AddField(
            model_name='disaster_location',
            name='Disaster_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetUtils.Disaster_Record'),
        ),
        migrations.AddField(
            model_name='disaster_location',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetUtils.Location'),
        ),
    ]
