# Generated by Django 2.0.2 on 2018-04-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TweetUtils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
    ]
