# Generated by Django 2.0.2 on 2018-04-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetUtils', '0002_auto_20180401_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet_info',
            name='Location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
