# Generated by Django 2.0.2 on 2018-04-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetUtils', '0003_tweet_info_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet_info',
            name='Location',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='tweet_info',
            name='Tweet_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tweet_info',
            name='Tweet_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
